<?php

namespace ContainerPUQe0r1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OJ_BvHAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oJ.BvHA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oJ.BvHA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorie' => ['privates', '.errored..service_locator.oJ.BvHA.App\\Entity\\Categorie', NULL, 'Cannot autowire service ".service_locator.oJ.BvHA": it needs an instance of "App\\Entity\\Categorie" but this type has been excluded in "config/services.yaml".'],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'categorie' => 'App\\Entity\\Categorie',
            'paginator' => '?',
        ]);
    }
}
