<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPUQe0r1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPUQe0r1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPUQe0r1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPUQe0r1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPUQe0r1\App_KernelDevDebugContainer([
    'container.build_hash' => 'PUQe0r1',
    'container.build_id' => '2a2a843d',
    'container.build_time' => 1680050350,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPUQe0r1');
