<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUsvjBa1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUsvjBa1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUsvjBa1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUsvjBa1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUsvjBa1\App_KernelDevDebugContainer([
    'container.build_hash' => 'UsvjBa1',
    'container.build_id' => 'fa6970a0',
    'container.build_time' => 1714081434,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUsvjBa1');
